export default [
  "Abril FatFace",
  "Alegreya",
  "Alegreya Sans",
  "Amatic SC",
  "Anonymous Pro",
  "Architects Daughter",
  "Archivo",
  "Archivo Narrow",
  "Asap",
  "Barlow",
  "BioRhyme",
  "Bonbon",
  "Cabin",
  "Cairo",
  "Cardo",
  "Chivo",
  "Concert One",
  "Cormorant",
  "Crimson Text",
  "Eczar",
  "Exo 2",
  "Fira Sans",
  "Fjalla One",
  "Frank Ruhl Libre",
  "Great Vibes",
  "Heebo",
  "IBM Plex",
  "Inconsolata",
  "Indie Flower",
  "Inknut Antiqua",
  "Inter",
  "Karla",
  "Libre Baskerville",
  "Libre Franklin",
  "Montserrat",
  "Neuton",
  "Notable",
  "Nothing You Could Do",
  "Noto Sans",
  "Nunito",
  "Old Standard TT",
  "Oxygen",
  "Pacifico",
  "Poppins",
  "Proza Libre",
  "PT Sans",
  "PT Serif",
  "Rakkas",
  "Reenie Beanie",
  "Roboto Slab",
  "Ropa Sans",
  "Rubik",
  "Shadows Into Light",
  "Space Mono",
  "Spectral",
  "Sue Ellen Francisco",
  "Titillium Web",
  "Ubuntu",
  "Varela",
  "Vollkorn",
  "Work Sans",
  "Yatra One",
];
